Stop releasing prescriptions as a container image
thoth-station/prescriptions pull request #17210
Opened 2021-09-14 07:57 UTC by fridex

#### What type of PR is this?

Related: https://github.com/thoth-station/prescriptions/issues/50

2021-09-14 07:59 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **fridex** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fprescriptions).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/prescriptions/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["fridex"]} -->

2021-09-20 07:20 UTC, fridex commented
/assign @harshad16

2021-09-20 13:30 UTC, harshad16 requested changes
lgtm
thanks , just one comment

2021-09-20 13:30 UTC, harshad16 commented on .aicoe-ci.yaml
>  - thoth-build
```suggestion
check: []
```

2021-09-20 13:31 UTC, fridex commented on .aicoe-ci.yaml
>  - thoth-build
Thanks 👍🏻

2021-09-23 13:11 UTC, harshad16 commented
@fridex can you please rebase 
i will review once again and merge it

2021-09-23 13:23 UTC, fridex commented
> @fridex can you please rebase
> i will review once again and merge it

Thanks, rebased now. 👍🏻

2021-09-23 13:36 UTC, harshad16 commented
@fridex rebase removed the change i had suggested
can you make the .aicoe-ci.yaml as
```
check: []
```

2021-09-23 13:41 UTC, fridex commented
Ah, sorry about that. Now pushed again with the change. PTAL

2021-09-23 13:48 UTC, harshad16 approved these changes
lgtm
thanks :100:

2021-09-23 13:50 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/thoth-station/prescriptions/pull/17210#pullrequestreview-762046505" title="Approved">harshad16</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fprescriptions).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/thoth-station/prescriptions/blob/master/OWNERS)~~ [harshad16]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-09-23 14:34 UTC, merged