Add pre-commit hooks using adviser
thoth-station/prescriptions pull request #38951
Opened 2023-01-17 10:17 UTC by VannTen

## Related Issues and Dependencies
fix #8
thoth-station/adviser#2402
## This introduces a breaking change

- No

## This should yield a new module release

- No

## This Pull Request implements

Add a pre-commit hooks to validate prescriptions.
In conjonction with --from-ref / --to-ref, this should only validates files touched in a PR

This on my fork of thoth-station/adviser because it needs thoth-station/adviser#2411 and thoth-station#2408 to be merged first.

By the way, we really need operate-first/apps#2462 on this repo. It would allow us to implement pre-commit hook caching instead of installing every single time, which would save a lot of prow-time. (well, once it comes back up...)

/hold

2023-01-17 10:35 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
**Once this PR has been reviewed and has the lgtm label**, please assign kpostoffice for approval by writing `/assign @kpostoffice` in a comment. For more information see [the Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fprescriptions).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/prescriptions/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["kpostoffice"]} -->

2023-01-17 10:46 UTC, sesheta commented
@VannTen: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | a37387fc2c3514bc4bd5335fd670dcdfd51f81fd | [link](https://prow.operate-first.cloud/view/s3/prow-c2ac1283-86c7-4ab4-babc-a07c8c4f1f79/prow-logs/pr-logs/pull/thoth-station_prescriptions/38951/pre-commit/1615298211918909440) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=prescriptions&pr=38951). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AVannTen). Please help us and [open an issue](https://github.com/thoth-station/prescriptions/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-01-20 08:12 UTC, goern commented
/test all

2023-01-20 08:30 UTC, sesheta commented
@VannTen: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | a37387fc2c3514bc4bd5335fd670dcdfd51f81fd | [link](https://prow.operate-first.cloud/view/s3/prow-c2ac1283-86c7-4ab4-babc-a07c8c4f1f79/prow-logs/pr-logs/pull/thoth-station_prescriptions/38951/pre-commit/1616350691469561856) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=prescriptions&pr=38951). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AVannTen). Please help us and [open an issue](https://github.com/thoth-station/prescriptions/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-03 10:28 UTC, VannTen commented
/unhold

2023-02-03 10:42 UTC, sesheta commented
@VannTen: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | e7c60fcc3c1dd15b71b436c6a2e49bc18448cc6d | [link](https://prow.operate-first.cloud/view/s3/prow-c2ac1283-86c7-4ab4-babc-a07c8c4f1f79/prow-logs/pr-logs/pull/thoth-station_prescriptions/38951/pre-commit/1621457030084562944) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=prescriptions&pr=38951). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AVannTen). Please help us and [open an issue](https://github.com/thoth-station/prescriptions/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-03 11:34 UTC, codificat requested changes
just one pre-commit thing to fix

2023-02-03 11:34 UTC, codificat commented on .pre-commit-config.yaml
> +      exclude: prescriptions/_prescription_metadata.yaml
yamllint is complaining: ` error    wrong indentation: expected 2 but found 4  (indentation) `

2023-02-03 12:24 UTC, VannTen commented
of course I had to forget the other pre-commit hooks :/

2023-02-03 13:38 UTC, codificat commented
/lgtm
/approve

thanks!

2023-02-03 13:38 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/thoth-station/prescriptions/pull/38951#issuecomment-1415882437" title="Approved">codificat</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fprescriptions).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/thoth-station/prescriptions/blob/master/OWNERS)~~ [codificat]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2023-02-03 13:43 UTC, merged